name: C/C++ CI

on:
  push:
    branches: [ github-ci-test ]
  pull_request:
    branches: [ github-ci-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cd tests; python ./build.py
