name: SO3-LVGL Performance
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk update
          apk add make cmake gcc-arm-none-eabi libc-dev bison flex bash patch mount dtc dosfstools u-boot-tools net-tools \
            bridge-utils iptables dnsmasq util-linux qemu-system-arm
      - name: SO3-LVGL build
        run: |
          blablaa
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/
          force_orphan: true
          
