name: SO3-LVGL Performance check
on: [push, pull_request, workflow_dispatch]
jobs:
  so3_lvgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake gcc-aarch64-none-elf device-tree-compiler u-boot-tools pkg-config bridge-utils qemu-system-aarch64
        version: 1.0

      - name: Remove useless dependency
      run: |
          sudo apt-get remove -y libyaml-dev
          
      - name: SO3-LVGL building components
      run: |
          wget https://github.com/smartobjectoriented/so3/archive/refs/heads/master.zip
          unzip master.zip
          mv so3-* so3
          cd so3
          patch -p1 < ci/so3_ci.patch
          
      - name: Docker execution   
      run: |
          docker build . -t so3/virt64 --platform linux/amd64
        

