
name: SO3-LVGL Performance check
on: [push, pull_request, workflow_dispatch]
jobs:
  so3_lvgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'lvgl'

      - name: SO3-LVGL building the Docker image
        run: |
          wget https://raw.githubusercontent.com/smartobjectoriented/so3/40-expand-and-document-lvgl-perf-tests/Dockerfile.lvgl
          pwd
          ls -la .
          docker build . -f Dockerfile.lvgl -t so3/virt64 --platform linux/amd64

      - name: SO3-LVL Running containerized performance check app
        run: docker run --privileged -v $PWD:/host -v /dev:/dev so3/virt64 
        
      - name: Download_artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_performance
          path: perf_check*.log

