name: Build Documentation

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-22.04
    name: Build docs
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Doxygen and Latex dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen texlive-xetex texlive-binaries texlive-lang-english latexmk fonts-freefont-otf

      - name: Install requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Cached Missing Docstrings
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: MISSING-DOCSTRINGS
          key: MISSING-DOCSTRINGS-v1

      - name: Build docs
        run: docs/build.py ignore-missing-warnings

      - uses: actions/upload-artifact@v4
        with:
          name: MISSING-DOCSTRINGS
          path: MISSING-DOCSTRINGS
          if-no-files-found: ignore
