name: Spelling

on:
  push:
    branches: [ master, release/v8.* ]
  pull_request:
    branches: [ master, release/v8.* ]

jobs:
  typos_check:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    name: Typos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Search for misspellings
        uses: crate-ci/typos@v1.16.20
